[package]
name = "yyz"
version = "0.1.0"
description = "Graph library"
repository = "https://github.com/daniel-levin/yyz"
authors = ["Daniel Levin <daniellevin2607@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
